### PR TITLE
Fixed issue #21 of having to install each dependency manually using pip install.

### PR DESCRIPTION
**Pull request by shreayan98c**
I have created a new python environment and created a requirements.txt file containing all the dependencies needed to run the codebase. Hence these dependencies need not be installed manually if the user doesn't have a python environment already set up. Also updated the readme markdowns to include how to install using the requirements.txt file.

### CODE REVIEW

**Comment by pranayjoshi** [comment]
@akshayLoginradius isn't this a minor text change. The same thing I did.

**Comment by DanBrown47** [comment]
@akshayLoginradius I have made the same PR, That too before @shreayan98c did and mine was noted as ineligible why is that?

**Comment by pranayjoshi** [comment]
Just like me...

**Comment by pranayjoshi** [comment]
@DanBrown47 same for me buddy...

**Comment by akshayLoginradius** [comment]
@shreayan98c thanks for your suggestion, we will include it in the next release.

**Pull request closed without merging**
