### PR TITLE
Updated Demo | Added requirements | Updated READMEs

### PR DESCRIPTION
**Pull request by pranayjoshi**
# Changes Made
* Added a standard ```requirements.txt```.
   * Added the ```requirements.txt``` for the ease of users. As they can install all the libraries required using a single command.
   * Added it using ``` pip freeze ```. So, there should no doubt about any errors.
   * Also, I tested it in the ``` venv ```.
* Updated ``` README.md ```
   * Updated the README file with new ```pip install -r requirements.txt``` command in place of installing all the libraries one by one.
* Removed some errors from the Documents i.e ``` Numbering spaces ```

### CODE REVIEW

**Comment by pranayjoshi** [comment]
Any response Maintainers??

**Comment by pranayjoshi** [comment]
Hello @SoniNow @ankiitsinghh07 @ashish8947 Please review this, it's been 21 days since I am waiting.

**Comment by pranayjoshi** [comment]
Why did yu mark it as ineligible

**Comment by pranayjoshi** [comment]
Its wrong. I was the first one to add all the Requirements.

**Comment by pranayjoshi** [comment]
I am seriously regretting to contribute to this Repo. And if you are thinking I am submitting due to Hacktober, than for your kind information I have already completed it. You merged the same changes made by a person 4 days ago. And just check when I created this repo.

**Comment by pranayjoshi** [comment]
Also I just saw the PR with merged changes, it consists only 5 packages, in ```requirements.txt```.

**Comment by pranayjoshi** [comment]
Please improve your service guys.

**Comment by akshayLoginradius** [comment]
@pranayjoshi 
Thanks for contributing to the repo. We can surely improve as per your suggestions. But as per the HacktoberFest guideline, we will not be accepting minor text fixes & the same content PR again. Please suggest and improve some quantifiable changes in the pull request to make your PR eligible for HacktoberFest.

**Pull request closed without merging**
