### PR TITLE
refactor: Formatted files according to PEP8 guidelines

### PR DESCRIPTION
**Pull request by devkapilbansal**
Formatted files using black and isort to follow pep8 guidelines

### CODE REVIEW

**Comment by devkapilbansal** [comment]
@ankiitsinghh07 @akshayLoginradius Please review this pull request.I have made changes in styling only without making changes in the codebase

**Comment by DanBrown47** [comment]
How come this is accepted but not my pull request @akshayLoginradius and for @devkapilbansal Please refer to hactoberfest guidlines, Adding spaces are not a good way to contribute to opensource.

**Comment by devkapilbansal** [comment]
@DanBrown47 I have followed PEP8 guidelines for this changes. Not just added spaces anywhere. Also, you should not be competitive. Rest you should ask maintainers why your pull request is not accepted in comments of pull request itself or a community channel if they have one.

**Comment by devkapilbansal** [comment]
Hi, @akshayLoginradius when the pull requests labelled with 'hacktoberfest-accepted' be merged

**Comment by akshayLoginradius** [comment]
@devkapilbansal  thanks for your suggestion, we will include it in the next release.

**Comment by devkapilbansal** [comment]
Thanks @akshayLoginradius for considering this

**Pull request closed without merging**
